#!/usr/bin/env bash

# Need to get docker environment variables from /proc,
# because systemd init do not pass them to service units
OIFS=$IFS; IFS=$(echo -en "\v")
for e in $(tr "\000" "\v"</proc/1/environ); do declare $e; done
IFS=$OIFS

if [ -n "$SSHUSER" ]; then

    if ! id -u $SSHUSER > /dev/null 2>&1; then
        useradd -ms /bin/bash $SSHUSER
    fi

    if [ -n "$SSHAUTHORIZEDKEY" ]; then

        mkdir -p /home/$SSHUSER/.ssh
        echo $SSHAUTHORIZEDKEY >> /home/$SSHUSER/.ssh/authorized_keys
    fi
fi
